 export const dummyMenuData = [
    {
      id: 1,
      title: "Paneer Butter Masala",
      image: "path_to_image/paneer_butter_masala.jpg", // You can provide the path to an actual image of the dish
      qty: 1,
      category: "Indian",
    },
    {
      id: 2,
      title: "Chole Bhature",
      image: "path_to_image/chole_bhature.jpg",
      qty: 1,
      category: "Indian",
    },
    {
      id: 3,
      title: "Butter Chicken",
      image: "path_to_image/butter_chicken.jpg",
      qty: 1,
      category: "Indian",
    },
    {
      id: 4,
      title: "Masala Dosa",
      image: "path_to_image/masala_dosa.jpg",
      qty: 1,
      category: "Indian",
    },
    {
      id: 5,
      title: "Pav Bhaji",
      image: "path_to_image/pav_bhaji.jpg",
      qty: 1,
      category: "Indian",
    },
    {
      id: 6,
      title: "Aloo Gobi",
      image: "path_to_image/aloo_gobi.jpg",
      qty: 1,
      category: "Indian",
    },
    {
      id: 7,
      title: "Samosa",
      image: "path_to_image/samosa.jpg",
      qty: 1,
      category: "Indian",
    },
    {
      id: 8,
      title: "Biryani",
      image: "path_to_image/biryani.jpg",
      qty: 1,
      category: "Indian",
    },
    {
      id: 9,
      title: "Tandoori Chicken",
      image: "path_to_image/tandoori_chicken.jpg",
      qty: 1,
      category: "Indian",
    },
    {
      id: 10,
      title: "Rogan Josh",
      image: "path_to_image/rogan_josh.jpg",
      qty: 1,
      category: "Indian",
    },
    {
      id: 11,
      title: "Dhokla",
      image: "path_to_image/dhokla.jpg",
      qty: 1,
      category: "Indian",
    },
    {
      id: 12,
      title: "Lassi",
      image: "path_to_image/lassi.jpg",
      qty: 1,
      category: "Indian",
    },
    {
      id: 13,
      title: "Dal Tadka",
      image: "path_to_image/dal_tadka.jpg",
      qty: 1,
      category: "Indian",
    },
    {
      id: 14,
      title: "Gulab Jamun",
      image: "path_to_image/gulab_jamun.jpg",
      qty: 1,
      category: "Indian",
    },
    {
      id: 15,
      title: "Pani Puri",
      image: "path_to_image/pani_puri.jpg",
      qty: 1,
      category: "Indian",
    },
  ];
  